# How to join together all Wikipedia project counts
hdfs.init()

WIKI_DIR <- "hdfs:/user/signose/project_counts_ez"
WIKIPEDIA_TS_FILE <- "wikipedia_ts_file.csv"

BG <- paste0(WIKI_DIR, "/bg.txt")
CS <- paste0(WIKI_DIR, "/cs.txt")
DA <- paste0(WIKI_DIR, "/da.txt")
DE <- paste0(WIKI_DIR, "/de.txt")
EL <- paste0(WIKI_DIR, "/el.txt")
EN <- paste0(WIKI_DIR, "/en.txt")
ES <- paste0(WIKI_DIR, "/es.txt")
ET <- paste0(WIKI_DIR, "/et.txt")
FI <- paste0(WIKI_DIR, "/fi.txt")
FR <- paste0(WIKI_DIR, "/fr.txt")
GA <- paste0(WIKI_DIR, "/ga.txt")
HR <- paste0(WIKI_DIR, "/hr.txt")
HU <- paste0(WIKI_DIR, "/hu.txt")
IS <- paste0(WIKI_DIR, "/is.txt")
IT <- paste0(WIKI_DIR, "/it.txt")
LT <- paste0(WIKI_DIR, "/lt.txt")
LV <- paste0(WIKI_DIR, "/lv.txt")
MK <- paste0(WIKI_DIR, "/mk.txt")
MT <- paste0(WIKI_DIR, "/mt.txt")
NL <- paste0(WIKI_DIR, "/nl.txt")
NO <- paste0(WIKI_DIR, "/no.txt")
PL <- paste0(WIKI_DIR, "/pl.txt")
PT <- paste0(WIKI_DIR, "/pt.txt")
RO <- paste0(WIKI_DIR, "/ro.txt")
RU <- paste0(WIKI_DIR, "/ru.txt")
SK <- paste0(WIKI_DIR, "/sk.txt")
SL <- paste0(WIKI_DIR, "/sl.txt")
SQ <- paste0(WIKI_DIR, "/sq.txt")
SR <- paste0(WIKI_DIR, "/sr.txt")
SV <- paste0(WIKI_DIR, "/sv.txt")
TR <- paste0(WIKI_DIR, "/tr.txt")


BG <- read_csv(BG, sep=" ", header = FALSE)
CS <- read_csv(CS, sep=" ", header = FALSE)
DA <- read_csv(DA, sep=" ", header = FALSE)
DE <- read_csv(DE, sep=" ", header = FALSE)
EL <- read_csv(EL, sep=" ", header = FALSE)
EN <- read_csv(EN, sep=" ", header = FALSE)
ES <- read_csv(ES, sep=" ", header = FALSE)
ET <- read_csv(ET, sep=" ", header = FALSE)
FI <- read_csv(FI, sep=" ", header = FALSE)
FR <- read_csv(FR, sep=" ", header = FALSE)
GA <- read_csv(GA, sep=" ", header = FALSE)
HR <- read_csv(HR, sep=" ", header = FALSE)
HU <- read_csv(HU, sep=" ", header = FALSE)
IS <- read_csv(IS, sep=" ", header = FALSE)
IT <- read_csv(IT, sep=" ", header = FALSE)
LT <- read_csv(LT, sep=" ", header = FALSE)
LV <- read_csv(LV, sep=" ", header = FALSE)
MK <- read_csv(MK, sep=" ", header = FALSE)
MT <- read_csv(MT, sep=" ", header = FALSE)
NL <- read_csv(NL, sep=" ", header = FALSE)
NO <- read_csv(NO, sep=" ", header = FALSE)
PL <- read_csv(PL, sep=" ", header = FALSE)
PT <- read_csv(PT, sep=" ", header = FALSE)
RO <- read_csv(RO, sep=" ", header = FALSE)
RU <- read_csv(RU, sep=" ", header = FALSE)
SK <- read_csv(SK, sep=" ", header = FALSE)
SL <- read_csv(SL, sep=" ", header = FALSE)
SQ <- read_csv(SQ, sep=" ", header = FALSE)
SR <- read_csv(SR, sep=" ", header = FALSE)
SV <- read_csv(SV, sep=" ", header = FALSE)
TR <- read_csv(TR, sep=" ", header = FALSE)

names(BG) <- c("time", "BG")
names(CS) <- c("time", "CS")
names(DA) <- c("time", "DA")
names(DE) <- c("time", "DE")
names(EL) <- c("time", "EL")
names(EN) <- c("time", "EN")
names(ES) <- c("time", "ES")
names(ET) <- c("time", "ET")
names(FI) <- c("time", "FI")
names(FR) <- c("time", "FR")
names(GA) <- c("time", "GA")
names(HR) <- c("time", "HR")
names(HU) <- c("time", "HU")
names(IS) <- c("time", "IS")
names(IT) <- c("time", "IT")
names(LT) <- c("time", "LT")
names(LV) <- c("time", "LV")
names(MK) <- c("time", "MK")
names(MT) <- c("time", "MT")
names(NL) <- c("time", "NL")
names(NO) <- c("time", "NO")
names(PL) <- c("time", "PL")
names(PT) <- c("time", "PT")
names(RO) <- c("time", "RO")
names(RU) <- c("time", "RU")
names(SK) <- c("time", "SK")
names(SL) <- c("time", "SL")
names(SQ) <- c("time", "SQ")
names(SR) <- c("time", "SR")
names(SV) <- c("time", "SV")
names(TR) <- c("time", "TR")

wikipedia_ts <- data.frame(BG, CS$CS, DA$DA, DE$DE, EL$EL, EN$EN, ES$ES, ET$ET, FI$FI, FR$FR, GA$GA, 
            HR$HR, HU$HU, IS$IS, IT$IT, LT$LT, LV$LV, MK$MK, MT$MT, NL$NL, NO$NO, PL$PL, 
            PT$PT, RO$RO, RU$RU, SK$SK, SL$SL, SQ$SQ, SR$SR, SV$SV, TR$TR)

names(wikipedia_ts) <- c("time", "bg", "cs", "da", "de", "el",
              "en", "es", "et", "fi", "fr",
              "ga", "hr", "hu", "is", "it", 
              "lt", "lv", "mk", "mt", "nl",
              "no", "pl", "pt", "ro", "ru", 
              "sk", "sl", "sq", "sr", "sv", 
              "tr") 

write.csv(wikipedia_ts, WIKIPEDIA_TS_FILE, row.names=FALSE, fileEncoding="utf-8")

                     